{
    "name": "Platform HRM",
    "version": "19.0.1.0.0",
    "summary": "Employee DB, self-service portal, leave management, sick-leave flow, onboarding.",
    "author": "Cognita Innovative",
    "license": "LGPL-3",
    "category": "Human Resources",
    "depends": ["hr", "hr_holidays", "hr_skills", "mail", "portal", "custom_platform_security"],
    "data": [
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/leave_types.xml",
        "data/hrm_crons.xml",
        "views/employee_views.xml",
        "views/leave_views.xml",
        "views/sick_leave_views.xml",
        "views/dashboard_views.xml",
        "views/portal_templates.xml",
        "views/menus.xml",
    ],
    "demo": ["data/demo/demo_hr.xml"],
    "installable": True,
    "application": False,
    "auto_install": False,
}
