"""Scoped API tokens for the React app and FastAPI services.

Security design:
  - The raw token is generated at create time and shown ONCE (not stored).
  - Only the SHA-256 hash is persisted.
  - Tokens are scoped: read | write | admin.
  - Tokens are linked to a specific service and an Odoo user they impersonate.
  - Tokens can expire and can be revoked at any time.
  - All token events are written to platform.audit.log.
"""

import hashlib
import logging
import secrets

from odoo import api, fields, models

_logger = logging.getLogger(__name__)

TOKEN_BYTES = 40  # 320 bits — URL-safe base64 produces 54-char tokens


class PlatformApiToken(models.Model):
    _name = "platform.api.token"
    _description = "Platform API Token"
    _order = "create_date desc"

    name = fields.Char("Label", required=True)
    company_id = fields.Many2one(
        "res.company", default=lambda s: s.env.company, required=True, index=True
    )
    user_id = fields.Many2one(
        "res.users",
        "Acts As (User)",
        required=True,
        help=(
            "The Odoo user whose permissions are applied when this token is used. "
            "Never use an admin user here unless absolutely required."
        ),
        ondelete="restrict",
    )
    service = fields.Selection(
        [
            ("react_app", "React Support App"),
            ("fastapi", "FastAPI Service"),
            ("webhook", "Incoming Webhook"),
            ("ci", "CI / Test Runner"),
            ("other", "Other"),
        ],
        required=True,
        default="other",
    )
    scope = fields.Selection(
        [
            ("read", "Read-only"),
            ("write", "Read + Write"),
            ("admin", "Admin (full access for this user)"),
        ],
        required=True,
        default="read",
    )
    token_hash = fields.Char(
        "Token Hash (SHA-256)",
        readonly=True,
        copy=False,
        help="Only the hash is stored — the raw token was shown once at creation.",
    )
    expires_at = fields.Datetime(
        "Expires At",
        help="Leave empty for a non-expiring token (not recommended for production).",
    )
    last_used_at = fields.Datetime(readonly=True)
    active = fields.Boolean(default=True)
    notes = fields.Text()

    @api.model
    def _hash_token(self, raw: str) -> str:
        return hashlib.sha256(raw.encode()).hexdigest()

    @api.model
    def _new_raw_token(self) -> str:
        return secrets.token_urlsafe(TOKEN_BYTES)

    @api.model_create_multi
    def create(self, vals_list):
        # The raw token is generated by the caller (normally the
        # platform.api.token.generate wizard, which displays it exactly once)
        # and only its hash is passed here. If no hash is supplied (e.g. a
        # programmatic create), generate one server-side; the raw value is
        # intentionally discarded — issue tokens via the wizard to see them.
        for vals in vals_list:
            if not vals.get("token_hash"):
                vals["token_hash"] = self._hash_token(self._new_raw_token())

        records = super().create(vals_list)

        for rec in records:
            self.env["platform.audit.log"].log(
                "token_issued",
                res_model=self._name,
                res_id=rec.id,
                res_name=rec.name,
                summary=f"API token '{rec.name}' issued for service '{rec.service}'",
                details={
                    "service": rec.service,
                    "scope": rec.scope,
                    "user_id": rec.user_id.id,
                    "expires_at": rec.expires_at.isoformat() if rec.expires_at else None,
                },
                severity="warning",
            )

        return records

    def action_revoke(self):
        """Immediately deactivate a token and log the event."""
        for rec in self:
            rec.active = False
            self.env["platform.audit.log"].log(
                "token_revoked",
                res_model=self._name,
                res_id=rec.id,
                res_name=rec.name,
                summary=f"API token '{rec.name}' revoked by {self.env.user.name}",
                details={"service": rec.service, "scope": rec.scope},
                severity="warning",
            )

    @api.model
    def verify_token(self, raw_token: str) -> "PlatformApiToken | bool":
        """Verify a bearer token and return the token record if valid.

        Returns False if invalid, expired, or revoked.
        """
        if not raw_token:
            return False
        token_hash = self._hash_token(raw_token)
        rec = self.sudo().search([("token_hash", "=", token_hash), ("active", "=", True)], limit=1)
        if not rec:
            return False
        if rec.expires_at and rec.expires_at < fields.Datetime.now():
            return False
        # Update last_used_at without triggering audit (noise)
        self.env.cr.execute(
            "UPDATE platform_api_token SET last_used_at = NOW() WHERE id = %s", [rec.id]
        )
        rec.invalidate_recordset(["last_used_at"])
        return rec

    @api.model
    def cron_cleanup_expired_tokens(self):
        """Deactivate tokens that have been expired or revoked for more than 90 days."""
        cutoff = fields.Datetime.subtract(fields.Datetime.now(), days=90)
        expired = self.sudo().search(
            [
                ("active", "=", False),
                ("write_date", "<", cutoff),
            ]
        )
        if expired:
            _logger.info("API token cleanup: removing %d stale token records", len(expired))
            expired.unlink()
