apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform.fullname" . }}-ai-gateway
  labels: {{- include "platform.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector: {{- include "platform.selectorLabels" (dict "component" "ai-gateway" "context" .) | nindent 4 }}
