apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "platform.fullname" . }}-integration-gateway
  labels: {{- include "platform.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.global.ingressClass | quote }}
spec:
  rules:
    - host: hooks.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "platform.fullname" . }}-integration-gateway
                port:
                  number: 8001
