apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "platform.fullname" . }}-odoo-data
  labels: {{- include "platform.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.odoo.storage }}
