apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform.fullname" . }}-support-app
  labels: {{- include "platform.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 80
  selector: {{- include "platform.selectorLabels" (dict "component" "support-app" "context" .) | nindent 4 }}
