{
    "name": "Platform Accounting Advanced",
    "version": "19.0.1.0.0",
    "summary": "CoA, journals, reports, period locks, BV annual accounts, audit-file export.",
    "author": "Cognita Innovative",
    "license": "LGPL-3",
    "category": "Accounting",
    "depends": ["account", "mail", "custom_accounting_basic", "custom_platform_security"],
    "data": [
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "views/fiscal_year_views.xml",
        "views/fixed_asset_views.xml",
        "views/budget_views.xml",
        "views/accrual_views.xml",
        "views/annual_accounts_views.xml",
        "wizards/audit_export_wizard.xml",
        "report/annual_accounts_report.xml",
        "views/dashboard_views.xml",
        "views/menus.xml",
        "views/reports_menu.xml",
        "views/reports_views.xml",
        "data/accrual_cron.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
