{
    "name": "Platform Inventory",
    "version": "19.0.1.0.0",
    "summary": "Products, warehouses, stock moves, purchase orders, valuation, reorder rules, count workflow, audit log.",
    "author": "Cognita Innovative",
    "license": "LGPL-3",
    "category": "Inventory",
    "depends": ["stock", "purchase_stock", "mail", "sale_stock", "custom_platform_security"],
    "data": [
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/inventory_config.xml",
        "views/product_views.xml",
        "views/stock_views.xml",
        "views/warehouse_views.xml",
        "views/stock_count_views.xml",
        "views/audit_log_views.xml",
        "views/dashboard_views.xml",
        "views/menus.xml",
    ],
    "demo": ["data/demo/demo_inventory.xml"],
    "installable": True,
    "application": False,
    "auto_install": False,
}
