{
    "name": "Platform Accounting Basic",
    "version": "19.0.1.0.0",
    "summary": "Invoicing, bank import (CSV/MT940/CAMT.053), AI reconciliation, incoming invoice OCR, recurring invoices, pro forma, CSV export, audit trail.",
    "author": "Cognita Innovative",
    "license": "LGPL-3",
    "category": "Accounting",
    "depends": ["account", "mail", "custom_ai_core", "custom_platform_security"],
    "data": [
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/ir_cron.xml",
        "report/proforma_report.xml",
        "wizards/bank_import_wizard.xml",
        "wizards/invoice_import_wizard.xml",
        "wizards/invoice_export_wizard.xml",
        "views/invoice_views.xml",
        "views/reconciliation_views.xml",
        "views/overview_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
