{
    "name": "Platform CRM",
    "version": "19.0.1.0.0",
    "summary": "Extended CRM with AI lead scoring, signing history, GDPR fields, dashboards.",
    "author": "Cognita Innovative",
    "license": "LGPL-3",
    "category": "Sales/CRM",
    "depends": ["crm", "sale_crm", "mail", "custom_ai_core", "custom_platform_security"],
    "data": [
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/crm_lead_sources.xml",
        "data/ir_cron.xml",
        "views/crm_campaign_views.xml",
        "views/lead_views.xml",
        "views/contact_views.xml",
        "views/dashboard_views.xml",
        "views/platform_dashboard_views.xml",
        "views/menus.xml",
    ],
    "demo": ["data/demo/demo_crm.xml"],
    "installable": True,
    "application": True,
    "auto_install": False,
}
