{
    "name": "Platform AI Core",
    "version": "19.0.1.0.0",
    "summary": "LLM provider abstraction, RAG pipeline, prompt store, AI audit log.",
    "author": "Cognita Innovative",
    "license": "LGPL-3",
    "category": "Technical",
    "depends": ["base", "mail", "web", "custom_platform_security"],
    "data": [
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/ai_providers.xml",
        "data/ai_prompt_templates.xml",
        "views/ai_provider_views.xml",
        "views/ai_prompt_views.xml",
        "views/ai_audit_views.xml",
        "views/ai_document_views.xml",
        "views/ai_feedback_views.xml",
        "views/res_company_views.xml",
        "views/menus.xml",
        "views/dashboard_views.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "external_dependencies": {
        "python": ["cryptography"],
        "python_optional": ["pdfminer.six", "python-docx"],
    },
}
