{
    "name": "Platform Helpdesk",
    "version": "19.0.1.0.0",
    "summary": "Tickets, SLA, AI classification and draft replies with approval workflow.",
    "author": "Cognita Innovative",
    "license": "LGPL-3",
    "category": "Services/Helpdesk",
    "depends": [
        "sale",
        "account",
        "crm",
        "mail",
        "portal",
        "custom_ai_core",
        "custom_platform_security",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/helpdesk_stages.xml",
        "views/ticket_views.xml",
        "views/sla_views.xml",
        "views/portal_templates.xml",
        "views/dashboard_views.xml",
        "views/menus.xml",
    ],
    "demo": ["data/demo/demo_data.xml"],
    "installable": True,
    "application": True,
    "auto_install": False,
}
